---
- name: Secure apt updates
  hosts: debian-linux
  gather_facts: false   # <- important, stops Python-based fact gathering

  tasks:
    - name: Update apt cache
      become: true
      command: apt-get update

    - name: Upgrade packages
      become: true
      command: apt-get -y dist-upgrade

    - name: Autoremove
      become: true
      command: apt-get -y autoremove
