---
- name: Update apt packages on Debian-based Linux
  hosts: debian-linux
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade apt packages (dist-upgrade)
      apt:
        upgrade: dist

    - name: Clean apt cache and autoremove
      apt:
        autoclean: yes
        autoremove: yes
